version: '3.8'

services:
  jenkins:
    image: myjenkins
    container_name: jenkins_container
    networks:
      - jenkins_network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "JENKINS_OPTS=--httpPort=8080" 
    ports:
      - "8080:8080"  
    

networks:
  jenkins_network:
    external: false
volumes:
  jenkins_home:
