apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
<<<<<<< HEAD
      - name: my-app
        image: my-app:1.0.0
=======
      - name: flaskapp
<<<<<<< HEAD
        image: dyang32/flask-app:latest  
>>>>>>> 9ea9be3 (fixed port ip for node port)
=======
        image: flask-app:latest
>>>>>>> d2c4ffc (changed host to all ports in app.y. docker.flaskapp exposed port changed and configured my deployment and node-port to match with targetting port)
        ports:
        - containerPort: 50000
