apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/jenkins_home/"
