apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
        - name: data-processor
          image: dyang32/data-processor:latest
          volumeMounts:
          - name: sensor-data-storage
            mountPath: "/my-pvc"
      volumes:
        - name: sensor-data-storage
          persistentVolumeClaim:
            claimName: sensor-data-pvc

