apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app

        image: dyang32/flask-app:latest

        ports:
        - containerPort: 50000
        volumeMounts:
        - name: sensor-data-storage
          mountPath: "/my-pv"
      volumes:
      - name: sensor-data-storage
        persistentVolumeClaim:
          claimName: sensor-data-pvc
